site_name: ImageFromTextGenerator
site_url: https://omarsamirz.github.io/ImageFromTextGenerator/

theme:
  name: material
  font: 
    text: Roboto
  favicon: assets/iftg_logo_small.png
  logo: assets/iftg_logo_small.png
  language: en  
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    # - header.autohide
    - announce.dismiss
    - navigation.footer
    # - navigation.path
    # - navigation.indexes
    - navigation.sidebar
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.instant.progress
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate

  palette:
    
    # Dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    
    # Light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  
copyright: Copyright &copy; 2024 Omar Samir
extra:
  generator: false

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting Started:
      - Installation: getting_started/installation.md
      - Tutorial: getting_started/tutorial.md
  - API Reference:
    - Adders:
      - NoiseAdder <b>Module</b>: reference/adders/noise_adder.md
      - ImageNoiseAdder <b>Module</b>: reference/adders/image_noise_adder.md
      - DirectoryNoiseAdder <b>Module</b>: reference/adders/directory_noise_adder.md
    - Creators:
      - Creator <b>Module</b>: reference/creators/creator.md
      - ImageCreator <b>Module</b>: reference/creators/image_creator.md
    - Generators:
      - Generator <b>Module</b>: reference/generators/generator.md
      - ImagesGenerator <b>Module</b>: reference/generators/images_generator.md
      - BatchesImagesGenerator <b>Module</b>: reference/generators/batches_images_generator.md
    - Noises: 
      - Noise <b>Module</b>: reference/noises/noise.md
      - BlurNoise <b>Module</b>: reference/noises/blur_noise.md
      - BrightnessNoise <b>Module</b>: reference/noises/brightness_noise.md
      - DilateNoise <b>Module</b>: reference/noises/dilate_noise.md
      - ElasticNoise <b>Module</b>: reference/noises/elastic_noise.md
      - ErodeNoise <b>Module</b>: reference/noises/erode_noise.md
      - FlipNoise <b>Module</b>: reference/noises/flip_noise.md
      - GaussianNoise <b>Module</b>: reference/noises/gaussian_noise.md
      - PixelDropoutNoise <b>Module</b>: reference/noises/pixel_dropout_noise.md
      - RotationNoise <b>Module</b>: reference/noises/rotation_noise.md
      - ShadowNoise <b>Module</b>: reference/noises/shadow_noise.md
    - ImageFontManager <b>Module</b>: reference/image_font_manager.md
    