site_name: ImageFromTextGenerator
site_url: https://omarsamirz.github.io/ImageFromTextGenerator/

theme:
  favicon: assets/iftg_logo.png
  logo: assets/iftg_logo.png
  name: material
  language: en  
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    # - header.autohide
    - announce.dismiss
    - navigation.path
    - navigation.indexes
    - navigation.sidebar
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.instant.progress
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate 

  palette:
    
    # Dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    
    # Light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  
copyright: Copyright &copy; 2024 Omar Samir
extra:
  generator: false

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting Started:
      - Installation: getting_started/installation.md
      - Tutorial: getting_started/tutorial.md
  - API Reference:
    - Adders:
      - NoiseAdder: reference/adders/noise_adder.md
      - DirectoryNoiseAdder: reference/adders/directory_noise_adder.md
    - Creators:
      - Creator: reference/creators/creator.md
      - ImageCreator: reference/creators/image_creator.md
    - Generators:
      - Generator: reference/generators/generator.md
      - ImagesGenerator: reference/generators/images_generator.md
      - BatchesImagesGenerator: reference/generators/batches_images_generator.md
    - Noises: reference/noises.md
    